outside_light:
  mode: auto
  timers:
    - "on":
        type: daily
        time: "06:55:00"

      "off":
        type: sunrise
        offset: -900

      minimum: 1800

    - "on":
        type: sunset
        offset: -1800

      "off":
        type: daily
        time: "21:50:00"

      minimum: 1800

socket1:
  mode: auto
  timers:
    - "on":
        type: daily
        time: "20:43:10"

      "off":
        type: daily
        time: "20:43:20"

overstair_light:
  mode: manual
  timers:
    - "on":
        type: daily
        time: "15:00:00"

      "off":
        type: daily
        time: "15:10:00"
